version: "3.9"
name: harmony
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - backend
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.0.120:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - backend
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    environment:
      - KAFKA_CLUSTERS_0_NAME=local-cluster # Имя кластера в UI
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka:9092 # Адрес Kafka в Docker-сети
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181 # Адрес Zookeeper (опционально)
      - KAFKA_CLUSTERS_0_SCHEMA_REGISTRY=http://localhost:8081 # (если используешь Schema Registry)
    ports:
      - "8080:8080"
    networks:
      - backend
  postgres:
    image: postgres:latest
    container_name: pg
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: harmony
    ports:
      - "5445:5432"
    networks:
      - backend
networks:
  backend:
    driver: bridge